modLoader="javafml"
loaderVersion="[36,]"
issueTrackerURL="https://github.com/Darkhax-Minecraft/Thirsty-Bottles/issues"
license="LGPL v2.1"

[[mods]]
modId="thirstybottles"
updateJSONURL="https://updates.blamejared.com/get?n=thirstybottles&gv=1.16.5"
version="${file.jarVersion}"
displayName="${modName}"
displayURL="${modHomepage}"
credits="${modCredits}"
authors="${modAuthor}"
description='''
${modDescription}
'''

[[dependencies.thirstybottles]]
    modId="forge"
    mandatory=true
    versionRange="[36,]"
    ordering="NONE"
    side="BOTH"

[[dependencies.thirstybottles]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"